### PR TITLE
DFBW - 45 Create an input atom

### PR DESCRIPTION
**Pull request by helbertoro**
# Input atom

## Decisions i should have made

1. boder color: --common-color-primary-light
2. boder color in focus: --common-color-secondary-light

The focus work in input border color and label color

### CODE REVIEW

**Comment by omarefg** [comment]
The conflicts need to be resolved before I can approve it.

**Comment by omarefg** [comment]
I agree with @AryRosvall, consider not uploading the package-lock.json in the PR.

**Comment by helbertoro** [comment]
Sorry it was a mistake, i deleted the file from the PR

**Comment by omarefg** [comment]
It still appear with conflicts.

**Pull request merged**
