### PR TITLE
DFBW - 40 Created Button Atom

### LINKED ISSUE #40: Create button atom
Create a button atom component in folder "components/atoms" that have general properties that can be reused in many components.

### PR DESCRIPTION
**Pull request by AryRosvall**
-  [x] I have followed the [Contributor guideline](https://github.com/Master-delta-force/bikeapp).
- [ ]  Tests are included
- [ ]  Documentation is changed or added
- [x]  Related issue has been created
- [x]  Commits messages follows [commit guideline](https://github.com/Master-delta-force/bikeapp) 

resolves #40

### CODE REVIEW

**Comment by omarefg** [comment]
Why this atom do not have styles? Or variants?

Reference image. 

image

**Comment by AryRosvall** [comment]
> Why this atom do not have styles? Or variants?
> 
> Reference image.
> 
> image

The idea is that you can add the class you need instead of forcing to use only the defined styles

**Comment by omarefg** [comment]
> > Why this atom do not have styles? Or variants?
> > Reference image.
> > image
> 
> The idea is that you can add the class you need instead of forcing to use only the defined styles

The idea of adding the class and overriding styles is great, but, don't you think this is the same of using a button tag? Why I would prefer using the atom then? Both gives me the same behavior.

**Comment by helbertoro** [comment]
> Adding button atom. Resolves issue #40.

Ary, i think the same of Omar, the button should be styles

**Comment by helbertoro** [comment]
Ary, what do you think about something like this 
`<button
    class:primary={type === 'primary'}
    class:secondary={type === 'secondary'}
    class:fixed={fixed}
    on:click={onClick}
>
    <slot></slot>
</button> `
@omarefg used it in some of his atoms

**Pull request merged**
